# docker-compose.yml
version: '3'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
